#!/bin/bash

# go to root
cd

# install wget and curl
sudo apt-get update

# install openvpn
wget -O /etc/openvpn/openvpn.tar "https://raw.githubusercontent.com/mysticvpn/openvpn/master/openvpn.tar"
cd /etc/openvpn/
tar xf openvpn.tar
wget -O /etc/openvpn/1194.conf "https://raw.githubusercontent.com/mysticvpn/openvpn/master/1194.conf"
service openvpn restart
sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
iptables -t nat -I POSTROUTING -s 192.168.100.0/24 -o eth0 -j MASQUERADE
iptables-save > /etc/iptables_yg_baru_dibikin.conf
wget -O /etc/network/if-up.d/iptables "https://raw.githubusercontent.com/mysticvpn/openvpn/master/iptables"
chmod +x /etc/network/if-up.d/iptables
service openvpn restart

# openvpn configuration
cd /etc/openvpn/
wget -O /etc/openvpn/client.ovpn "https://raw.githubusercontent.com/mysticvpn/openvpn/master/client-1194.conf"
sed -i $MYIP2 /etc/openvpn/client.ovpn;
cp client.ovpn /home/vps/public_html/

# install squid3
cd
sudo apt-get install squid
wget -O /etc/squid/squid.conf "https://raw.githubusercontent.com/mysticvpn/openvpn/master/squid3.conf"
sed -i $MYIP2 /etc/squid/squid.conf;
service squid restart

# install webmin
cd
sudo su -c 'echo "deb http://download.webmin.com/download/repository sarge contrib"> /etc/apt/sources.list.d/webmin.list'
wget http://www.webmin.com/jcameron-key.asc
sudo apt-key add jcameron-key.asc
sudo apt update -y
sudo apt install -y webmin

END

# banner
rm /etc/issue.net
wget -O /etc/issue.net "https://raw.githubusercontent.com/mysticvpn/openvpn/master/issue.net"
sed -i 's@#Banner@Banner@g' /etc/ssh/sshd_config
service ssh restart

echo "0 0 * * * root /sbin/reboot" > /etc/cron.d/reboot

# finishing
cd
service openvpn restart
service cron restart
service ssh restart
service squid3 restart
service webmin restart
